language: go
go_import_path: github.com/prysmaticlabs/prysm
sudo: false
matrix:
  include:
    - os: linux
      go: 1.11.x
      env:
        - lint
      install:
        - go get ${gobuild_args} -t ./...
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0
      script:
        - golangci-lint run
      email: false
      after_success:
        - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
      after_failure:
        - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL
